name: Generate Modpack

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version for the modpack'
        required: true

jobs:
  generate_modpack:
    runs-on: ubuntu-latest

    steps:
    - name: Set up input parameters
      id: input
      run: |
        echo "::set-output name=release_version::$INPUT_RELEASE_VERSION"

    - name: Checkout code
      uses: actions/checkout@v2


    - name: Copy files to modpack directory
      run: |
        mkdir -p modpack/
        cp -r mods config scripts modpack/
        echo "overrides" > modpack/overrides
        
    - name: Download HBM
      id: download
      run: |
        wget -O modpack/mods/hbm-1.8.3a-G.jar "https://github.com/TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT/releases/download/hbm-1.8.3a-G/hbm-1.8.3a-G.jar"

    - name: Create manifest.json
      run: |
        # Read the template manifest.json and replace the variables
        RELEASE_VERSION="${{ steps.input.outputs.release_version }}"
        cat << EOF > modpack/manifest.json
        {
          "minecraft": {
            "version": "1.12.2",
            "modLoaders": [
              {
                "id": "forge-14.23.5.2859",
                "primary": true
              }
            ]
          },
          "manifestType": "minecraftModpack",
          "manifestVersion": 1,
          "name": "Mechanical Sorcery",
          "version": "$RELEASE_VERSION",
          "author": "Compec Someoneidk 0mori Nibiru",
          "files": [
            {
              "projectID": 123, // Replace with the actual project ID of the mod on the hosting platform
              "fileID": 456    // Replace with the actual file ID of the mod on the hosting platform
            }
          ],
          "overrides": "overrides"
        }
        EOF

    - name: Upload modpack artifact
      uses: actions/upload-artifact@v2
      with:
        name: "Mechanical Sorcery"
        path: "modpack"
